-- CREATE DATABASE music_db;

CREATE TABLE songs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    src VARCHAR(255) NOT NULL,
    cover VARCHAR(255) NOT NULL,
    -- lyrics TEXT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
